democart/config/routes.rb
Rails.application.routes.draw do
  
  root 'users#new'

  
  resources :users do
    member do
      get 'dashboard'
    end
  end

  resources :sessions, only: [:new, :create, :destroy]

  get 'login' => 'sessions#new', as: 'login'
  get 'signup' => 'users#new', as: 'signup'
  get 'logout' => 'sessions#destroy', as: 'logout'

end

democart/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

democart/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :name,:password, presence: true, length: { minimum: 5 }
  validates :email, presence: { message: "must be given please" }, length: { minimum: 6 }

end

democart/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
  
end

democart/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to dashboard_user_path(user.id), notice: "Logged in!"
    else
      flash.now[:alert] = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end

end

democart/app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    redirect_to new_session_path
  end

  def new
    @user = User.new
  end

  def dashboard

  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

democart/app/helpers/application_helper.rb
module ApplicationHelper
end

democart/app/helpers/sessions_helper.rb
module SessionsHelper
end

democart/app/helpers/users_helper.rb
module UsersHelper
end

democart/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Democart</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

democart/app/views/users/dashboard.html.erb
<h1> This is DashBoard of User </h1>

<% if current_user %>
  Logged in as <%= current_user.email %>
  <%= link_to 'Log Out', logout_path %>
<% else %>
  <%= link_to 'Sign Up', signup_path %> 
  <%= link_to 'Log In', login_path %>
<% end %>
<p id=”notice”><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
        <td><%= link_to 'Show', dashboard_user_path %></td>
        <td><%= link_to 'Edit', dashboard_user_path %></td>
        <td><%= link_to 'Destroy', dashboard_user_path, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        
  </tbody>

</table>

democart/app/views/users/new.html.erb
<h1>Enter Details</h1>
<%= form_for @user, url: users_path, method: :post do |f| %>

<% if @user.errors.any? %>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
<% end %>

<%= f.label :name, "Full Name" %>
<%= f.text_field :name, class: 'form-control' %>  <br />

<%= f.label :email, "Email ID" %>
<%= f.text_field :email, class: 'form-control' %>  <br />

<%= f.label :password, "Password" %>
<%= f.password_field :password,  class: 'form-control' %>  <br />

<%= f.label :password_confirmation, "Confirm Password" %>
<%= f.password_field :password_confirmation,  class: 'form-control' %>  <br />

<%= f.submit "Create account", class: "button CreateAccount" %>

<% end %>

<p>
<h3>Already a Member!! Sign In Here</h3>
<%= button_to "Sign In", new_session_path, :method => "get" %>
</p>