electroshop/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: 'users/sessions' }
  resources :products 
  get 'products/home'

  root 'products#home'
end

electroshop/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

electroshop/app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
end

electroshop/app/models/user.rb
class User < ApplicationRecord
  has_many :products
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

electroshop/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

electroshop/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = current_user.products
  end

  def show
  end

  def home
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id
    if @product.save
      redirect_to @product
      flash[:notice] = "Product created"
    else
      render :new
    end
  end

  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Product updated.'
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to @product, notice: 'Product destroyed.'
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :price, :description)
  end
end

electroshop/app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

electroshop/app/helpers/application_helper.rb
module ApplicationHelper
end

electroshop/app/helpers/products_helper.rb
module ProductsHelper
end

electroshop/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> Electroshop </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: "alert alert-info" %>
    <% end %>
    <%= yield %>
  </body>
</html>

electroshop/app/views/products/_details.html.erb
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

electroshop/app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

electroshop/app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

electroshop/app/views/products/home.html.erb
<p>
  <a style="font-family:Comic Sans MS; color:#FF0000" href="#">ELECTROCART</a> || 
  <% if current_user %>
    Logged in as: <a style="font-family:Comic Sans MS; color:#FF0000; text-align: right"> <%= current_user.email %></a> || <%= link_to 'Signout', destroy_user_session_path %>
  <% else %>
    <%= link_to 'Signin', user_session_path %>
  <% end %>
</p>

<table>
  <thead>
    <tr>
      <th>Name </th>
      <th>Price </th>
      <th>Description </th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= product.description %></td>

        <td><%= link_to 'Show', product %></td>

      </tr>
    <% end %>
  </tbody>
</table>

electroshop/app/views/products/index.html.erb
<p><a href="#">DashBoard</a> || <%= link_to 'Setting', edit_user_registration_path %> || Logged in as: <a style="font-family:Comic Sans MS; color:#FF0000; text-align: right"><%= current_user.email %></a> || <%= link_to 'Logout', destroy_user_session_path, data: { confirm: 'Are you sure want to logout?' }, method: :delete %></p>
<br>

<h1>Your Products :</h1>
<%= link_to 'Add New Product', new_product_path %>
<br>

<table>
  <thead>
    <tr>
      <th>Name </th>
      <th>Price </th>
      <th>Description </th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= product.description %></td>

        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product.id) %></td>
        <td><%= link_to 'Destroy', product_path(product.id), data: { confirm: 'Are you sure?' }, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

electroshop/app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

electroshop/app/views/products/show.html.erb
<%= render 'details', product: @product %>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>