mycartapp/config/routes.rb
Rails.application.routes.draw do

  get 'products/home'
  get 'products/details'
  get 'products/new'
  get 'seller/dashboard'
  match 'seller/new', via: [:get, :post]
  post 'seller/create'
  get 'seller/show'
  get 'login/identity'
  get 'login/logindetails'
  post 'login/create'
  get 'login/login'

  resources :users
  resources :product
  root 'login#identity'
end

mycartapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

mycartapp/app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true, length: { minimum: 5 }

end

mycartapp/app/models/seller.rb
class Seller < ApplicationRecord
  has_secure_password

  validates :name,:password, presence: true, length: { minimum: 5 }
  validates :mobile_no, presence: true, length: { minimum: 10 },uniqueness: true, numericality: { only_integer: true }
  validates :email_id, presence: { message: "must be given please" }, length: { minimum: 6 }
end

mycartapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :warning, :danger, :info
end

mycartapp/app/controllers/login_controller.rb
class SessionsController < ApplicationController
  
  def identity
  end

  def logindetails
  end

  def create
    @seller = Seller.where(email_id: params[:email_id]).first
    
    if @seller && @seller.authenticate(params[:password])
     session[:seller_id] = @seller.id
     redirect_to products_home_path, :notice => "Logged in successfully"
    else
     flash[:danger] = 'Not authenticated'
     render :action => 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to login_logindetails_path, :notice => "You successfully logged out"
  end

end

mycartapp/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  #http_basic_authenticate_with name: "dj", password: "123", except: [:home, :details]
  #http_basic_authenticate_with name: "dj", password: "1234", only: :destroy
  def home
    @products = Product.all
  end

  def details
    @product = Product.find(params[:id])
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if  @product.save
        redirect_to @product
    else
        render 'new'
    end
  end

private
  def product_params
    params.require(:product).permit(:name,:details,:quantity,:price)
  end
end

mycartapp/app/controllers/seller_controller.rb
class SellerController < ApplicationController
  def dashboard
    @products = Product.all
  end
  
  def show
    @seller = Seller.find(params[:id])
  end

  def new
    @seller = Seller.new
  end

  def create
    @seller = Seller.new(seller_params)
    if @seller.save
      redirect_to seller_dashboard_path
    else
      render 'new'
    end
  end

private
  def seller_params
    params.require(:seller).permit(:name,:email_id,:mobile_no,:password)
  end
end

mycartapp/app/helpers/application_helper.rb
module ApplicationHelper
 
end

mycartapp/app/helpers/login_helper.rb
module LoginHelper
end

mycartapp/app/helpers/products_helper.rb
module ProductsHelper
end

mycartapp/app/helpers/seller_details_helper.rb
module SellerDetailsHelper
end

mycartapp/app/helpers/seller_helper.rb
module SellerHelper
end

mycartapp/app/helpers/sessions_helper.rb
module SessionsHelper
end

mycartapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mycartapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

mycartapp/app/views/login/identity.html.erb
<h1>Welcome to Shopping cart application</h1>
<%= image_tag ("/assets/cart.jpg"),:size => '400x400' , class: "img-responsive"%>
<p>If you are Seller
<%= link_to 'Click Here', "login/logindetails" %>
</p>





<!--
<p>If you are Buyer
<%= link_to 'Click Here', "products/home" %>
</p>
-->

mycartapp/app/views/login/logindetails.html.erb
<h1>Enter Login Credentials</h1>

<%= form_tag login_create_path, method: :post do %>

<%= label_tag :email_id, "Email ID" %>
<%= text_field_tag :email_id, nil, class: 'form-control' %>  <br />

<%= label_tag :password, "Password" %>
<%= text_field_tag :password, nil, class: 'form-control' %>  <br />

<%= submit_tag "Login", class: "button CreateAccount" %>  <br />

<% end %>

<p>
<h3>Not a Member!! Sign Up Here</h3>
<%= button_to "Signup", seller_new_path, :method => "get" %>
</p>

mycartapp/app/views/products/details.html.erb
<h1>Product Details</h1>

<p>
	<strong>Product Name:</strong>
	<%= @product.name %>
</p>
<p>
	<strong>Product Details:</strong>
	<%= @product.details %>
</p>
<p>
	<strong>Product Quantity Available:</strong>
	<%= @product.quantity %>
</p>
<p>
	<strong>Product price:</strong>
	<%= @product.price %>
</p>
<%= link_to 'Back', products_home_path %>

mycartapp/app/views/products/home.html.erb
<h1>Products on Website</h1>
<h1>Listing Products</h1>
 
<table>
  <tr>
    <th>Name</th>
    <th>Details</th>
    <th>Quantity</th>
    <th>Price</th>
    <th></th>
  </tr>
 
  <% @products.each do |product| %>
    <tr>
      <td><%= product.name %></td>
      <td><%= product.details %></td>
      <td><%= product.quantity %></td>
      <td><%= product.price %></td>
      <td><%= link_to 'Show', product_path(product) %></td>
    </tr>
  <% end %>
</table>

mycartapp/app/views/products/new.html.erb
<%= form_with scope: :product, url: seller_dashboard_path, local: true do |form| %>
  
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :details %><br>
    <%= form.text_area :details %>
  </p>
 
  <p>
    <%= form.label :quantity %><br>
    <%= form.text_area :quantity %>
  </p>

  <p>
    <%= form.label :price %><br>
    <%= form.text_area :price %>
  </p>

  <p>
    <%= form.add %>
  </p>
<% end %>

<%= link_to 'Back', seller_dashboard_path %>

mycartapp/app/views/seller/dashboard.html.erb
<h1>This is Your DashBoard:</h1>
<h1>Listing Products</h1>
 <%= link_to 'Add New Product', seller_new_path %>
<table>
  <tr>
    <th>Name</th>
    <th>Details</th>
    <th>Quantity</th>
    <th>Price</th>
    <th></th>
  </tr>
 
  <% @products.each do |product| %>
    <tr>
      <td><%= product.name %></td>
      <td><%= product.details %></td>
      <td><%= product.quantity %></td>
      <td><%= product.price %></td>
      <td><%= link_to 'Show', seller_new_path(product) %></td>
    </tr>
  <% end %>
</table>

mycartapp/app/views/seller/new.html.erb
<h1>Enter Details</h1>
<%= form_for @seller, url: seller_create_path, method: :post do |f| %>

<% if @seller.errors.any? %>
      <% @seller.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
<% end %>

<br />
<%= f.label :name, "Full Name" %>
<%= f.text_field :name, class: 'form-control' %>  <br />

<%= f.label :email_id, "Email ID" %>
<%= f.text_field :email_id, class: 'form-control' %>  <br />

<%= f.label :mobile_no, "Mobile Number" %>
<%= f.text_field :mobile_no, class: 'form-control' %>  <br />

<%= f.label :password, "Password" %>
<%= f.text_field :password,  class: 'form-control' %>  <br />

<%= f.submit "Create account", class: "button CreateAccount" %>  <br />

<% end %>

mycartapp/app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>